### DISCUSSION TITLE
How do i reduce the gap between the top of the waybar and the bottom of the open window?

### DISCUSSION THREAD

**Discussion by ayakashi-perhaps** [prasanthrangan/hyprdots#1785] [Q&A]
![image](https://github.com/user-attachments/assets/c3c158d6-c336-489e-9789-44bcc152eb2b)
i wanted to reduce this gap right here and i tried editing style.css in my waybar config but that didn't seem to work.
I'm using a pretty much a stock install of hyprdots minus a different wallpaper and the clear waybar
```css
@import "theme.css";

window#waybar {
    background: @bar-bg;
    padding: 0;
    margin: 0;
    height: 16px;
}

tooltip {
    background: @main-bg;
    color: @main-fg;
    border-radius: ${t_radius}px;
    border-width: 0px;
    padding: 0;
    margin 0;
    height: 16px;
}
```
this is what the waybar part of my style.css looks like
