### ISSUE TITLE
Change or add as option installing shell

### ISSUE THREAD

**Issue by RAprogramm** [prasanthrangan/hyprdots#566]
What about zsh alternatives?
I'm using [fish](https://fishshell.com/docs/current/index.html) + [starship](https://starship.rs/) + [lsd](https://github.com/lsd-rs/lsd)

![231127_18h35m04s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/70325462/70984724-cdf7-4ee7-8563-0f857a749911)

**Comment by T-Crypt** [comment]
What are you suggesting? Something like the ability for users to pick there shell?

**Comment by RAprogramm** [comment]
> What are you suggesting? Something like the ability for users to pick their shell? 

Yes,  something like that

**Comment by Balssh** [comment]
There is room for what you suggest, but I think it would require a bit of deciding whether to maintain both powerlevel10k and starship, whether to use lsd or eza etc.

**Comment by RAprogramm** [comment]
> There is room for what you suggest, but I think it would require a bit of deciding whether to maintain both powerlevel10k and starship, whether to use lsd or eza etc.

I was thinking of offering the user a choice during installation

**Comment by kRHYME7** [comment]
How about having a separate way like "patching it? "  So we could still have the maintainers default. Also maybe maintainable. as if the patch may fail we still have the  default as fallbacks.

**Comment by prasanthrangan** [comment]
I like this feature, will definitely implement this... so that user can use either zsh or fish!

**Comment by prasanthrangan** [comment]
hey @RAprogramm , could you please share your fish + starship config.
I'll try to add it to install script this week.

**Comment by RAprogramm** [comment]
"Sorry, I've had a lot going on. I'll do it within the next day, my friend."

**Comment by RAprogramm** [comment]
## starship

starship with default config
---
## fish

config.fish
```fish
if status is-interactive
    starship init fish | source
end
```
---
fish_plugins
```fish
jorgebucaran/autopair.fish
patrickf1/colored_man_pages.fish
jethrokuan/z
```
plugins installed via [fisher](https://github.com/joxji/fisher)
---
## lsd

config.yaml
```yaml
classic: false

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: auto
  theme: custom

date: '+%A, %d %B %Y, %R'

# == Dereference ==
# Whether to dereference symbolic links.
# Possible values: false, true
dereference: false

# == Icons ==
icons:
  when: auto
  # Which icon theme to use.
  # Possible values: fancy, unicode
  theme: fancy
  # Separator between icon and the name
  # Default to 1 space
  separator: ' '

# == Ignore Globs ==
# A list of globs to ignore when listing.
# ignore-globs:
#   - .git

# == Indicators ==
# Whether to add indicator characters to certain listed files.
# Possible values: false, true
indicators: false

layout: grid

# == Recursion ==
recursion:
  # Whether to enable recursion.
  # Possible values: false, true
  enabled: false
  # How deep the recursion should go. This has to be a positive integer. Leave
  # it unspecified for (virtually) infinite.
  # depth: 3

size: default

permission: rwx

# == Sorting ==
sorting:
  column: name
  reverse: false
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first

# == No Symlink ==
# Whether to omit showing symlink targets
# Possible values: false, true
no-symlink: false

# == Total size ==
# Whether to display the total size of directories.
# Possible values: false, true
total-size: true

# == Hyperlink ==
# Attach hyperlink to filenames
# Possible values: always, auto, never
hyperlink: never

# == Symlink arrow ==
# Specifies how the symlink arrow display, chars in both ascii and utf8
symlink-arrow: ⇒

# == Header ==
# Whether to display block headers.
# Possible values: false, true
header: true
```
---
colors.yaml
```yaml
user: 230
group: 187
permission:
  read: dark_yellow
  write: dark_blue
  exec: dark_green
  exec-sticky: 5
  no-access: 245
  octal: 6
  acl: dark_cyan
  context: cyan
date:
  hour-old: 40
  day-old: 42
  older: 36
size:
  none: 245
  small: 229
  medium: 216
  large: 172
inode:
  valid: 13
  invalid: 245
links:
  valid: 13
  invalid: 245
tree-edge: 245
```
---
icons.yaml
```yaml
name:
  .trash: 
  .cargo: 󱣘
  .emacs.d: 
  a.out: 
extension:
  go: 
  hs: 
  rs: 
  lua: 
  md: 
  pdf: 
  png: 
filetype:
  dir: 
  file: 
  pipe: 󰟥
  socket: 󰐧
  executable: 
  symlink-dir: 
  symlink-file: 
  device-char: 
  device-block: 󰜫
  special: 

```
